# Generated by Django 5.1.7 on 2025-03-14 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pengguna', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='biodata',
            old_name='User',
            new_name='user',
        ),
    ]
